dist: focal
language: shell
services:
  - docker
before_install:
  - source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/split/dkr.sh)
script:
  - dkr_dockerhub_ratelimit
  - docker pull golang:1.16-alpine
  - dkr_dockerhub_ratelimit
  - docker pull alpine:latest
  - dkr_dockerhub_ratelimit
  - dkr_build
  - dkr_dockerhub_ratelimit
after_success:
  - dkr_push
  - dkr_dockerhub_ratelimit
