dist: focal
language: shell
services:
  - docker
before_install:
  - source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/split/dkr.sh)
script:
  - dkr_dockerhub_ratelimit
  - dkr_build
after_success:
  - dkr_push
  - dkr_dockerhub_ratelimit

