dist: bionic
language: shell
# env:
#   global:
#   - INPUT_BUILDOPTIONS="--build-arg REGISTRY_BASE=ghcr.io/jesusfcro/"
services:
  - docker
before_install:
  - source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/split/docker.sh)
script:
  - docker_build
after_success:
  - docker_push
