dist: focal
language: shell
services:
  - docker
before_install:
  - source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/split/dkr.sh)
  - DKRTOKEN=$(curl --user "$DOCKER_USERNAME:$DOCKER_PASSWORD" "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" | jq -r .token)
script:
  - curl --head -H "Authorization: Bearer $DKRTOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest
  - dkr_build
  - curl --head -H "Authorization: Bearer $DKRTOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest
after_success:
  - dkr_push
  - curl --head -H "Authorization: Bearer $DKRTOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest

