dist: bionic
language: shell
services:
  - docker
before_install:
  - source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/split/docker.sh)
script:
  - cicd_build
after_success:
  - cicd_push
