dist: bionic
language: shell
env:
  global:
    - DOCKER_BUILDKIT=1
services:
  - docker
before_install:
  - source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/split/docker.sh)
script:
  - docker_build
after_success:
  - docker_push
